# Generated by Django 4.0.6 on 2022-07-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music2',
        ),
    ]
