# Generated by Django 4.0.6 on 2022-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_name',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
