# Generated by Django 4.0.6 on 2022-07-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_news_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_name',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
